linters:
  Indentation:
    character: space # or 'tab'
    width: 4
  HexLength:
    enabled: false
  IdSelector:
    enabled: false
  NestingDepth:
    max_depth: 4
  ColorVariable:
    enabled: false
