enum DNAType {
    PROMOTER,               //'DNAType.PROMOTER';
    RIBOSOME_BINDING_SITE,  //'DNAType.RIBOSOME_BINDING_SITE';
    START_CODON,            //'DNAType.START_CODON';
    PROTEINKODENDE_SEKVENS, //'DNAType.PROTEINKODENDE_SEKVENS';
    STOP_CODON,             //'DNAType.STOP_CODON';
    TERMINATOR              //'DNAType.TERMINATOR';
}

export = DNAType;
